all:
	pdflatex report.tex
	pdflatex report.tex
final:
	pdflatex -jobname COL774_Assignment-1 report.tex
	pdflatex -jobname COL774_Assignment-1 report.tex
.PHONY: clean
clean:
	rm *.aux
	rm *.log
	rm *.out
